import { jsPDF } from "jspdf";

export const generateHarvesterPDF = (job, farmer) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  // Header
  doc.setFontSize(22);
  doc.setTextColor(27, 58, 107); // Navy #1B3A6B
  doc.text("SMART UZHAVAN", pageWidth / 2, 20, { align: "center" });
  
  doc.setFontSize(12);
  doc.setTextColor(100);
  doc.text("Harvester Bill / அறுவடை ரசீது", pageWidth / 2, 28, { align: "center" });
  doc.line(20, 32, pageWidth - 20, 32);

  // Bill Info
  doc.setFontSize(10);
  doc.setTextColor(0);
  doc.text(`Bill ID: ${job.billId}`, 20, 45);
  doc.text(`Date: ${new Date().toLocaleDateString()}`, pageWidth - 20, 45, { align: "right" });

  // Farmer Info
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text("Farmer Details:", 20, 60);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text(`Name: ${farmer?.name || "N/A"}`, 20, 68);
  doc.text(`Village: ${job.village || farmer?.village || "N/A"}`, 20, 75);

  // Job Details Table Header
  doc.setFillColor(240, 240, 240);
  doc.rect(20, 85, pageWidth - 40, 10, "F");
  doc.setFont("helvetica", "bold");
  doc.text("Description", 25, 91);
  doc.text("Qty/Hours", 120, 91);
  doc.text("Rate", 150, 91);
  doc.text("Amount", 180, 91);

  // Job Content
  doc.setFont("helvetica", "normal");
  let y = 102;
  doc.text(`Harvesting (${job.machineType})`, 25, y);
  doc.text(`${job.totalHours.toFixed(2)} Hrs`, 120, y);
  doc.text(`${job.ratePerHour}`, 150, y);
  doc.text(`${job.grossAmount.toFixed(2)}`, 180, y);

  if (job.discount > 0) {
    y += 10;
    doc.text("Discount", 25, y);
    doc.text(`- ${job.discount.toFixed(2)}`, 180, y);
  }

  doc.line(20, y + 5, pageWidth - 20, y + 5);
  
  // Total
  y += 15;
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("Total Amount (Net):", 120, y);
  doc.text(`Rs. ${job.finalAmount.toFixed(2)}`, 180, y);

  // Payments Section
  if (job.payments && job.payments.length > 0) {
    y += 15;
    doc.setFontSize(12);
    doc.text("Payment History:", 20, y);
    doc.setFontSize(9);
    job.payments.forEach(p => {
      y += 7;
      doc.text(`${p.date} - ${p.mode}`, 25, y);
      doc.text(`${p.amount.toFixed(2)}`, 180, y);
    });
  }

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(150);
  doc.text("Generated by SmartUzhavan System", pageWidth / 2, doc.internal.pageSize.getHeight() - 10, { align: "center" });

  doc.save(`${job.billId}.pdf`);
};

export const generateRentalPDF = (rental, farmer) => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
  
    doc.setFontSize(22);
    doc.setTextColor(27, 58, 107);
    doc.text("SMART UZHAVAN", pageWidth / 2, 20, { align: "center" });

    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text("Machinery Rental Bill", pageWidth / 2, 28, { align: "center" });
    doc.line(20, 32, pageWidth - 20, 32);

    doc.setFontSize(10);
    doc.setTextColor(0);
    doc.text(`Bill ID: ${rental.id}`, 20, 45);
    doc.text(`Farmer: ${farmer?.name}`, 20, 52);
    doc.text(`Machine: ${rental.machineType}`, 20, 59);
    doc.text(`Total: Rs. ${rental.totalAmount}`, 150, 70);
    
    doc.save(`Rental_${rental.id}.pdf`);
};
