const PDFDocument = require('pdfkit');
const path = require('path');
const fs = require('fs');

// Path to Tamil font in the new backend structure
const FONT_PATH = path.join(__dirname, '..', 'assets', 'fonts', 'NotoSansTamil.ttf');

const formatCurrency = (val) => `Rs. ${parseFloat(val || 0).toLocaleString('en-IN', { minimumFractionDigits: 2 })}`;

// Safety function to check if font is valid
const isFontValid = (filePath) => {
    if (!fs.existsSync(filePath)) return false;
    const stats = fs.statSync(filePath);
    return stats.size > 10240; // Must be > 10KB
};

const setupDoc = (doc) => {
    // Load Font with Safety Guard
    if (isFontValid(FONT_PATH)) {
        doc.font(FONT_PATH);
    } else {
        console.warn('Tamil font is missing or invalid. Falling back to Helvetica.');
        doc.font('Helvetica');
    }
};

const generateHarvesterBill = async (job, farmer) => {
    return new Promise((resolve, reject) => {
        const doc = new PDFDocument({ margin: 50, size: 'A4' });
        const buffers = [];
        
        doc.on('data', buffers.push.bind(buffers));
        doc.on('end', () => resolve(Buffer.concat(buffers)));
        doc.on('error', reject);

        setupDoc(doc);

        // Header
        doc.rect(0, 0, doc.page.width, 100).fill('#1B3A6B');
        doc.fillColor('white').fontSize(24).text('SMART UZHAVAN', 50, 30, { align: 'center' });
        doc.fontSize(12).text('Harvester Bill / அறுவடை ரசீது', 50, 65, { align: 'center' });

        doc.fillColor('black').moveDown(4);

        // Info Section
        const topY = 130;
        doc.fontSize(10);
        
        doc.fillColor('#1B3A6B').text('Farmer Details / விவசாயி விவரம்', 50, topY);
        doc.fillColor('black').text(`Name: ${farmer?.name || 'N/A'}`, 50, topY + 20);
        doc.text(`ID: ${farmer?.id || farmer?._id || 'N/A'}`, 50, topY + 35);
        doc.text(`Village: ${farmer?.village || 'N/A'}`, 50, topY + 50);

        doc.fillColor('#1B3A6B').text('Bill Information', 350, topY);
        doc.fillColor('black').text(`Bill ID: ${job.billId}`, 350, topY + 20);
        doc.text(`Date: ${new Date(job.date).toLocaleDateString()}`, 350, topY + 35);
        doc.text(`Season: ${job.season} ${job.seasonYear}`, 350, topY + 50);

        // Table Header
        const tableY = 220;
        doc.rect(50, tableY, 500, 20).fill('#F7FAFC');
        doc.fillColor('#1B3A6B').fontSize(10);
        doc.text('Description / விவரம்', 60, tableY + 5);
        doc.text('Qty/Hrs', 300, tableY + 5, { width: 100, align: 'right' });
        doc.text('Amount', 440, tableY + 5, { width: 100, align: 'right' });

        // Table Body
        doc.fillColor('black').fontSize(10);
        doc.text(`Harvesting (${job.machineType})`, 60, tableY + 30);
        doc.text(`${parseFloat(job.totalHours).toFixed(2)} Hrs`, 300, tableY + 30, { width: 100, align: 'right' });
        doc.text(formatCurrency(job.grossAmount), 440, tableY + 30, { width: 100, align: 'right' });

        if (job.discount > 0) {
            doc.fillColor('red').text('Discount / தள்ளுபடி', 60, tableY + 50);
            doc.text(`- ${formatCurrency(job.discount)}`, 440, tableY + 50, { width: 100, align: 'right' });
        }

        // Summary Line
        const summaryY = 320;
        doc.moveTo(50, summaryY).lineTo(550, summaryY).stroke('#E2E8F0');

        doc.fillColor('black').fontSize(12).text('Final Total / மொத்த தொகை:', 300, summaryY + 20);
        doc.text(formatCurrency(job.finalAmount), 440, summaryY + 20, { width: 100, align: 'right' });

        // Payments
        if (job.payments && job.payments.length > 0) {
            doc.moveDown(4);
            doc.fillColor('#1B3A6B').fontSize(12).text('Payment History / பணம் செலுத்திய விவரம்');
            doc.moveDown();
            job.payments.forEach(p => {
                doc.fillColor('black').fontSize(10).text(`${new Date(p.date).toLocaleDateString()} - ${p.mode} : ${formatCurrency(p.amount)}`, { indent: 20 });
            });
        }

        doc.fontSize(8).fillColor('#A0AEC0').text('Generated by SmartUzhavan Digital System', 50, 750, { align: 'center' });
        doc.end();
    });
};

const generateStatement = async (farmer, jobs, rentals) => {
    return new Promise((resolve, reject) => {
        const doc = new PDFDocument({ margin: 50, size: 'A4' });
        const buffers = [];
        
        doc.on('data', buffers.push.bind(buffers));
        doc.on('end', () => resolve(Buffer.concat(buffers)));
        doc.on('error', reject);

        setupDoc(doc);

        doc.rect(0, 0, doc.page.width, 100).fill('#1B3A6B');
        doc.fillColor('white').fontSize(24).text('SMART UZHAVAN', 50, 30, { align: 'center' });
        doc.fontSize(12).text('Account Statement / கணக்கு அறிக்கை', 50, 65, { align: 'center' });

        doc.fillColor('black').moveDown(4);

        const totalBill = (jobs || []).reduce((s, j) => s + (parseFloat(j.finalAmount) || 0), 0) + 
                         (rentals || []).reduce((s, r) => s + (parseFloat(r.totalAmount) || 0), 0);
        const totalPaid = [...(jobs || []), ...(rentals || [])].reduce((s, item) => 
                         s + (item.payments || []).reduce((pSum, p) => pSum + (parseFloat(p.amount) || 0), 0), 0);

        doc.fontSize(10).text(`Farmer: ${farmer.name} (${farmer.id || farmer._id})`, 50, 130);
        doc.text(`Village: ${farmer.village}`, 50, 145);
        doc.text(`Generated: ${new Date().toLocaleDateString()}`, 350, 130, { align: 'right' });

        doc.rect(50, 180, 150, 60).fill('#F7FAFC');
        doc.fillColor('black').text('Total Billed', 60, 190);
        doc.fontSize(14).text(formatCurrency(totalBill), 60, 210);

        doc.rect(225, 180, 150, 60).fill('#F0FFF4');
        doc.fillColor('green').fontSize(10).text('Total Paid', 235, 190);
        doc.fontSize(14).text(formatCurrency(totalPaid), 235, 210);

        doc.rect(400, 180, 150, 60).fill('#FFF5F5');
        doc.fillColor('red').fontSize(10).text('Outstanding / நிலுவை', 410, 190);
        doc.fontSize(14).text(formatCurrency(totalBill - totalPaid), 410, 210);

        doc.moveDown(8);
        doc.fillColor('#1B3A6B').fontSize(12).text('Transaction History');
        doc.moveDown();

        const tableY = 280;
        doc.fontSize(10).fillColor('black');
        doc.text('Date', 50, tableY);
        doc.text('Description', 150, tableY);
        doc.text('Billed', 350, tableY, { width: 60, align: 'right' });
        doc.text('Paid', 420, tableY, { width: 60, align: 'right' });
        doc.text('Balance', 490, tableY, { width: 60, align: 'right' });

        let currentY = tableY + 20;
        const allItems = [...(jobs || []), ...(rentals || [])].sort((a, b) => new Date(b.date || b.createdAt) - new Date(a.date || a.createdAt));

        allItems.forEach(item => {
            const itemPaid = (item.payments || []).reduce((s, p) => s + (parseFloat(p.amount) || 0), 0);
            const itemTotal = parseFloat(item.finalAmount || item.totalAmount) || 0;

            doc.fontSize(9).text(new Date(item.date || item.createdAt).toLocaleDateString(), 50, currentY);
            doc.text(item.billId || item.machineType, 150, currentY);
            doc.text(itemTotal.toFixed(0), 350, currentY, { width: 60, align: 'right' });
            doc.text(itemPaid.toFixed(0), 420, currentY, { width: 60, align: 'right' });
            doc.text((itemTotal - itemPaid).toFixed(0), 490, currentY, { width: 60, align: 'right' });
            
            currentY += 20;
            if (currentY > 750) {
                doc.addPage();
                currentY = 50;
            }
        });

        doc.end();
    });
};

const generateRentalReceipt = async (rental, farmer) => {
    return new Promise((resolve, reject) => {
        const doc = new PDFDocument({ margin: 50, size: 'A4' });
        const buffers = [];
        
        doc.on('data', buffers.push.bind(buffers));
        doc.on('end', () => resolve(Buffer.concat(buffers)));
        doc.on('error', reject);

        setupDoc(doc);

        doc.rect(0, 0, doc.page.width, 100).fill('#1B3A6B');
        doc.fillColor('white').fontSize(24).text('SMART UZHAVAN', 50, 30, { align: 'center' });
        doc.fontSize(12).text('Rental Receipt / வாடகை ரசீது', 50, 65, { align: 'center' });

        doc.fillColor('black').moveDown(4);

        const topY = 130;
        doc.fontSize(10);
        
        doc.fillColor('#1B3A6B').text('Farmer Details', 50, topY);
        doc.fillColor('black').text(`Name: ${farmer?.name || 'N/A'}`, 50, topY + 20);
        doc.text(`ID: ${farmer?.id || farmer?._id || 'N/A'}`, 50, topY + 35);
        doc.text(`Village: ${farmer?.village || 'N/A'}`, 50, topY + 50);

        doc.fillColor('#1B3A6B').text('Receipt Info', 350, topY);
        doc.fillColor('black').text(`Receipt ID: ${rental._id || rental.id}`, 350, topY + 20);
        doc.text(`Date: ${new Date(rental.date || rental.createdAt).toLocaleDateString()}`, 350, topY + 35);

        const tableY = 220;
        doc.rect(50, tableY, 500, 20).fill('#F7FAFC');
        doc.fillColor('#1B3A6B').text('Equipment / உபகரணம்', 60, tableY + 5);
        doc.text('Duration', 300, tableY + 5, { width: 100, align: 'right' });
        doc.text('Amount', 440, tableY + 5, { width: 100, align: 'right' });

        doc.fillColor('black').text(rental.machineType || 'Equipment Rental', 60, tableY + 30);
        doc.text(`${rental.quantity || 1} ${rental.unit || 'Units'}`, 300, tableY + 30, { width: 100, align: 'right' });
        doc.text(formatCurrency(rental.totalAmount), 440, tableY + 30, { width: 100, align: 'right' });

        const summaryY = 320;
        doc.moveTo(50, summaryY).lineTo(550, summaryY).stroke('#E2E8F0');
        doc.fontSize(12).text('Total Amount:', 300, summaryY + 20);
        doc.text(formatCurrency(rental.totalAmount), 440, summaryY + 20, { width: 100, align: 'right' });

        if (rental.payments && rental.payments.length > 0) {
            doc.moveDown(4);
            doc.fillColor('#1B3A6B').fontSize(12).text('Payment History / பணம் செலுத்திய விவரம்');
            doc.moveDown();
            rental.payments.forEach(p => {
                doc.fillColor('black').fontSize(10).text(`${new Date(p.date).toLocaleDateString()} - ${p.mode} : ${formatCurrency(p.amount)}`, { indent: 20 });
            });
        }

        doc.end();
    });
};

const generateDriverSalaryStatement = async (driver, salaryRecords, fromDate, toDate) => {
    return new Promise((resolve, reject) => {
        const doc = new PDFDocument({ margin: 50, size: 'A4' });
        const buffers = [];
        
        doc.on('data', buffers.push.bind(buffers));
        doc.on('end', () => resolve(Buffer.concat(buffers)));
        doc.on('error', reject);

        setupDoc(doc);
        
        doc.fontSize(18).fillColor('#1B3A6B').text('Driver Salary Statement', { align: 'center' });
        doc.moveDown();
        doc.fontSize(11).fillColor('black').text(`Driver: ${driver.name}`);
        doc.text(`Village: ${driver.village || 'N/A'}`);
        const period = fromDate && toDate ? `${fromDate} to ${toDate}` : 'All Records';
        doc.text(`Period: ${period}`);
        doc.moveDown();
        
        const col1 = 50, col2 = 130, col3 = 180, col4 = 230, col5 = 280, col6 = 330, col7 = 380, col8 = 430;
        doc.fontSize(10).fillColor('#1B3A6B');
        doc.text('Date', col1, doc.y);
        doc.text('Base', col2, doc.y);
        doc.text('Bonus', col3, doc.y);
        doc.text('Extra', col4, doc.y);
        doc.text('Adv', col5, doc.y);
        doc.text('Net', col6, doc.y);
        doc.text('Paid', col7, doc.y);
        doc.text('Bal', col8, doc.y);
        doc.moveTo(50, doc.y + 12).lineTo(550, doc.y + 12).stroke();
        doc.moveDown();

        let totalNetPay = 0, totalPaid = 0;
        doc.fontSize(9).fillColor('black');
        (salaryRecords || []).forEach(salary => {
            const netPay = (parseFloat(salary.baseSalary) || 0) + (parseFloat(salary.bonus) || 0) + (parseFloat(salary.extraAmount) || 0) - (parseFloat(salary.advance) || 0);
            const paid = (salary.payments || []).reduce((sum, p) => sum + (parseFloat(p.amount) || 0), 0);
            totalNetPay += netPay;
            totalPaid += paid;
            
            doc.text(new Date(salary.date).toLocaleDateString(), col1, doc.y);
            doc.text(salary.baseSalary.toFixed(0), col2, doc.y);
            doc.text(salary.bonus.toFixed(0), col3, doc.y);
            doc.text(salary.extraAmount.toFixed(0), col4, doc.y);
            doc.text(salary.advance.toFixed(0), col5, doc.y);
            doc.text(netPay.toFixed(0), col6, doc.y);
            doc.text(paid.toFixed(0), col7, doc.y);
            doc.text((netPay - paid).toFixed(0), col8, doc.y);
            doc.moveDown();
        });
        
        doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke();
        doc.fontSize(10).text('TOTAL', col1, doc.y + 5);
        doc.text(totalNetPay.toFixed(0), col6, doc.y + 5);
        doc.text(totalPaid.toFixed(0), col7, doc.y + 5);
        doc.text((totalNetPay - totalPaid).toFixed(0), col8, doc.y + 5);

        doc.end();
    });
};

const generateMonthlyReport = async (month, year, incomeRows, expenseRows, totals) => {
    return new Promise((resolve, reject) => {
        const doc = new PDFDocument({ margin: 40, size: 'A4' });
        const buffers = [];
        doc.on('data', buffers.push.bind(buffers));
        doc.on('end', () => resolve(Buffer.concat(buffers)));
        doc.on('error', reject);
        setupDoc(doc);
        
        doc.fontSize(16).fillColor('#1B3A6B').text(`Monthly Summary - ${month}/${year}`, { align: 'center' });
        doc.moveDown();
        
        doc.fontSize(12).text('Income by Source', { underline: true });
        let totalIncome = 0;
        (incomeRows || []).forEach(row => {
            const amount = parseFloat(row.amount) || 0;
            totalIncome += amount;
            doc.fontSize(9).text(`${row.source}: ${formatCurrency(amount)}`);
        });
        doc.fontSize(10).text(`Total Income: ${formatCurrency(totalIncome)}`, { bold: true });
        doc.moveDown();
        
        doc.fontSize(12).text('Expense by Source', { underline: true });
        let totalExpense = 0;
        (expenseRows || []).forEach(row => {
            const amount = parseFloat(row.amount) || 0;
            totalExpense += amount;
            doc.fontSize(9).text(`${row.source}: ${formatCurrency(amount)}`);
        });
        doc.fontSize(10).text(`Total Expense: ${formatCurrency(totalExpense)}`, { bold: true });
        doc.moveDown();
        
        doc.fontSize(12).text(`Net Profit: ${formatCurrency(totalIncome - totalExpense)}`, { align: 'center' });
        doc.end();
    });
};

const generateWorkerIndividualReport = async (worker, entries) => {
    return new Promise((resolve, reject) => {
        const doc = new PDFDocument({ margin: 40, size: 'A4' });
        const buffers = [];
        doc.on('data', buffers.push.bind(buffers));
        doc.on('end', () => resolve(Buffer.concat(buffers)));
        doc.on('error', reject);
        setupDoc(doc);

        doc.fontSize(16).fillColor('#1B3A6B').text(`Worker Report - ${worker.name}`, { align: 'center' });
        doc.fontSize(10).fillColor('black').text(`Village: ${worker.village || 'N/A'} | Phone: ${worker.phone || 'N/A'}`);
        doc.moveDown();
        
        const col1 = 50, col2 = 130, col3 = 190, col4 = 250, col5 = 310, col6 = 370, col7 = 430;
        doc.fontSize(8).text('Date', col1, doc.y);
        doc.text('Work Type', col2, doc.y);
        doc.text('Base', col3, doc.y);
        doc.text('Bonus', col4, doc.y);
        doc.text('Extra', col5, doc.y);
        doc.text('Adv', col6, doc.y);
        doc.text('Net', col7, doc.y);
        doc.moveTo(50, doc.y + 10).lineTo(550, doc.y + 10).stroke();
        doc.moveDown();

        let totalNet = 0;
        (entries || []).forEach(e => {
            const net = (e.baseSalary || 0) + (e.bonus || 0) + (e.extraAmount || 0) - (e.advance || 0);
            totalNet += net;
            doc.text(new Date(e.date).toLocaleDateString(), col1, doc.y);
            doc.text(e.workType || 'N/A', col2, doc.y);
            doc.text(e.baseSalary.toFixed(0), col3, doc.y);
            doc.text(e.bonus.toFixed(0), col4, doc.y);
            doc.text(e.extraAmount.toFixed(0), col5, doc.y);
            doc.text(e.advance.toFixed(0), col6, doc.y);
            doc.text(net.toFixed(0), col7, doc.y);
            doc.moveDown();
        });
        doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke();
        doc.fontSize(10).text(`Total Earnings: ${formatCurrency(totalNet)}`, 350, doc.y + 10);
        
        doc.end();
    });
};

module.exports = {
    generateHarvesterBill,
    generateStatement,
    generateRentalReceipt,
    generateDriverSalaryStatement,
    generateMonthlyReport,
    generateWorkerIndividualReport
};
