const PDFDocument = require('pdfkit');
const path = require('path');
const fs = require('fs');

// Path to Tamil font
const FONT_PATH = path.join(__dirname, 'fonts', 'NotoSansTamil.ttf');

const formatCurrency = (val) => `Rs. ${parseFloat(val || 0).toLocaleString('en-IN', { minimumFractionDigits: 2 })}`;

// Safety function to check if font is valid (minimum size for a TTF)
const isFontValid = (filePath) => {
    if (!fs.existsSync(filePath)) return false;
    const stats = fs.statSync(filePath);
    return stats.size > 10240; // Must be > 10KB
};

const generateHarvesterBill = async (job, farmer) => {
    return new Promise((resolve, reject) => {
        const doc = new PDFDocument({ margin: 50, size: 'A4' });
        const buffers = [];
        
        doc.on('data', buffers.push.bind(buffers));
        doc.on('end', () => resolve(Buffer.concat(buffers)));
        doc.on('error', reject);

        // Load Font with Safety Guard
        if (isFontValid(FONT_PATH)) {
            doc.font(FONT_PATH);
        } else {
            console.warn('Tamil font is missing or invalid (81-byte placeholder detected). Falling back to Helvetica to prevent crash.');
            doc.font('Helvetica');
        }

        // Header
        doc.rect(0, 0, doc.page.width, 100).fill('#1B3A6B');
        doc.fillColor('white').fontSize(24).text('SMART UZHAVAN', 50, 30, { align: 'center' });
        doc.fontSize(12).text('Harvester Bill / அறுவடை ரசீது', 50, 65, { align: 'center' });

        doc.fillColor('black').moveDown(4);

        // Info Section
        const topY = 130;
        doc.fontSize(10);
        
        // Left Column (Farmer)
        doc.fillColor('#1B3A6B').text('Farmer Details / விவசாயி விவரம்', 50, topY);
        doc.fillColor('black').text(`Name: ${farmer?.name || 'N/A'}`, 50, topY + 20);
        doc.text(`ID: ${farmer?.id || 'N/A'}`, 50, topY + 35);
        doc.text(`Village: ${farmer?.village || 'N/A'}`, 50, topY + 50);

        // Right Column (Bill)
        doc.fillColor('#1B3A6B').text('Bill Information', 350, topY);
        doc.fillColor('black').text(`Bill ID: ${job.billId}`, 350, topY + 20);
        doc.text(`Date: ${job.date}`, 350, topY + 35);
        doc.text(`Season: ${job.season} ${job.seasonYear}`, 350, topY + 50);

        // Table Header
        const tableY = 220;
        doc.rect(50, tableY, 500, 20).fill('#F7FAFC');
        doc.fillColor('#1B3A6B').fontSize(10);
        doc.text('Description / விவரம்', 60, tableY + 5);
        doc.text('Qty/Hrs', 300, tableY + 5, { width: 100, align: 'right' });
        doc.text('Amount', 440, tableY + 5, { width: 100, align: 'right' });

        // Table Body
        doc.fillColor('black').fontSize(10);
        doc.text(`Harvesting (${job.machineType})`, 60, tableY + 30);
        doc.text(`${parseFloat(job.totalHours).toFixed(2)} Hrs`, 300, tableY + 30, { width: 100, align: 'right' });
        doc.text(formatCurrency(job.grossAmount), 440, tableY + 30, { width: 100, align: 'right' });

        if (job.discount > 0) {
            doc.fillColor('red').text('Discount / தள்ளுபடி', 60, tableY + 50);
            doc.text(`- ${formatCurrency(job.discount)}`, 440, tableY + 50, { width: 100, align: 'right' });
        }

        // Summary Line
        const summaryY = 320;
        doc.moveTo(50, summaryY).lineTo(550, summaryY).stroke('#E2E8F0');

        doc.fillColor('black').fontSize(12).text('Final Total / மொத்த தொகை:', 300, summaryY + 20);
        doc.text(formatCurrency(job.finalAmount), 440, summaryY + 20, { width: 100, align: 'right' });

        // Payments
        if (job.payments && job.payments.length > 0) {
            doc.moveDown(4);
            doc.fillColor('#1B3A6B').fontSize(12).text('Payment History / பணம் செலுத்திய விவரம்');
            doc.moveDown();
            job.payments.forEach(p => {
                doc.fillColor('black').fontSize(10).text(`${p.date} - ${p.mode} : ${formatCurrency(p.amount)}`, { indent: 20 });
            });
        }

        // Footer
        doc.fontSize(8).fillColor('#A0AEC0').text('Generated by SmartUzhavan Digital System', 50, 750, { align: 'center' });

        doc.end();
    });
};

const generateStatement = async (farmer, jobs, rentals) => {
    return new Promise((resolve, reject) => {
        const doc = new PDFDocument({ margin: 50, size: 'A4' });
        const buffers = [];
        
        doc.on('data', buffers.push.bind(buffers));
        doc.on('end', () => resolve(Buffer.concat(buffers)));
        doc.on('error', reject);

        if (isFontValid(FONT_PATH)) {
            doc.font(FONT_PATH);
        } else {
            doc.font('Helvetica');
        }

        // Header
        doc.rect(0, 0, doc.page.width, 100).fill('#1B3A6B');
        doc.fillColor('white').fontSize(24).text('SMART UZHAVAN', 50, 30, { align: 'center' });
        doc.fontSize(12).text('Account Statement / கணக்கு அறிக்கை', 50, 65, { align: 'center' });

        doc.fillColor('black').moveDown(4);

        // Summary Box
        const totalBill = (jobs || []).reduce((s, j) => s + (parseFloat(j.finalAmount) || 0), 0) + 
                         (rentals || []).reduce((s, r) => s + (parseFloat(r.totalAmount) || 0), 0);
        const totalPaid = [...(jobs || []), ...(rentals || [])].reduce((s, item) => 
                         s + (item.payments || []).reduce((pSum, p) => pSum + (parseFloat(p.amount) || 0), 0), 0);

        doc.fontSize(10).text(`Farmer: ${farmer.name} (${farmer.id})`, 50, 130);
        doc.text(`Village: ${farmer.village}`, 50, 145);
        doc.text(`Generated: ${new Date().toLocaleDateString()}`, 350, 130, { align: 'right' });

        // Financial Cards
        doc.rect(50, 180, 150, 60).fill('#F7FAFC');
        doc.fillColor('black').text('Total Billed', 60, 190);
        doc.fontSize(14).text(formatCurrency(totalBill), 60, 210);

        doc.rect(225, 180, 150, 60).fill('#F0FFF4');
        doc.fillColor('green').fontSize(10).text('Total Paid', 235, 190);
        doc.fontSize(14).text(formatCurrency(totalPaid), 235, 210);

        doc.rect(400, 180, 150, 60).fill('#FFF5F5');
        doc.fillColor('red').fontSize(10).text('Outstanding / நிலுவை', 410, 190);
        doc.fontSize(14).text(formatCurrency(totalBill - totalPaid), 410, 210);

        // Transaction Table
        doc.moveDown(8);
        doc.fillColor('#1B3A6B').fontSize(12).text('Transaction History');
        doc.moveDown();

        const tableY = 280;
        doc.fontSize(10).fillColor('black');
        doc.text('Date', 50, tableY);
        doc.text('Description', 150, tableY);
        doc.text('Billed', 350, tableY, { width: 60, align: 'right' });
        doc.text('Paid', 420, tableY, { width: 60, align: 'right' });
        doc.text('Balance', 490, tableY, { width: 60, align: 'right' });

        let currentY = tableY + 20;
        const allItems = [...(jobs || []), ...(rentals || [])].sort((a, b) => new Date(b.date || b.createdAt) - new Date(a.date || a.createdAt));

        allItems.forEach(item => {
            const itemPaid = (item.payments || []).reduce((s, p) => s + (parseFloat(p.amount) || 0), 0);
            const itemTotal = parseFloat(item.finalAmount || item.totalAmount) || 0;

            doc.fontSize(9).text(item.date || item.createdAt || 'N/A', 50, currentY);
            doc.text(item.billId || item.machineType, 150, currentY);
            doc.text(itemTotal.toFixed(0), 350, currentY, { width: 60, align: 'right' });
            doc.text(itemPaid.toFixed(0), 420, currentY, { width: 60, align: 'right' });
            doc.text((itemTotal - itemPaid).toFixed(0), 490, currentY, { width: 60, align: 'right' });
            
            currentY += 20;
        });

        doc.end();
    });
};

const generateRentalReceipt = async (rental, farmer) => {
    return new Promise((resolve, reject) => {
        const doc = new PDFDocument({ margin: 50, size: 'A4' });
        const buffers = [];
        
        doc.on('data', buffers.push.bind(buffers));
        doc.on('end', () => resolve(Buffer.concat(buffers)));
        doc.on('error', reject);

        if (isFontValid(FONT_PATH)) {
            doc.font(FONT_PATH);
        } else {
            doc.font('Helvetica');
        }

        // Header
        doc.rect(0, 0, doc.page.width, 100).fill('#1B3A6B');
        doc.fillColor('white').fontSize(24).text('SMART UZHAVAN', 50, 30, { align: 'center' });
        doc.fontSize(12).text('Rental Receipt / வாடகை ரசீது', 50, 65, { align: 'center' });

        doc.fillColor('black').moveDown(4);

        // Info Section
        const topY = 130;
        doc.fontSize(10);
        
        doc.fillColor('#1B3A6B').text('Farmer Details', 50, topY);
        doc.fillColor('black').text(`Name: ${farmer?.name || 'N/A'}`, 50, topY + 20);
        doc.text(`ID: ${farmer?.id || 'N/A'}`, 50, topY + 35);
        doc.text(`Village: ${farmer?.village || 'N/A'}`, 50, topY + 50);

        doc.fillColor('#1B3A6B').text('Receipt Info', 350, topY);
        doc.fillColor('black').text(`Receipt ID: ${rental.id}`, 350, topY + 20);
        doc.text(`Date: ${rental.date || rental.createdAt}`, 350, topY + 35);

        // Table
        const tableY = 220;
        doc.rect(50, tableY, 500, 20).fill('#F7FAFC');
        doc.fillColor('#1B3A6B').text('Equipment / உபகரணம்', 60, tableY + 5);
        doc.text('Duration', 300, tableY + 5, { width: 100, align: 'right' });
        doc.text('Amount', 440, tableY + 5, { width: 100, align: 'right' });

        doc.fillColor('black').text(rental.machineType || 'Equipment Rental', 60, tableY + 30);
        doc.text(`${rental.quantity || 1} ${rental.unit || 'Days'}`, 300, tableY + 30, { width: 100, align: 'right' });
        doc.text(formatCurrency(rental.totalAmount), 440, tableY + 30, { width: 100, align: 'right' });

        // Total
        const summaryY = 320;
        doc.moveTo(50, summaryY).lineTo(550, summaryY).stroke('#E2E8F0');
        doc.fontSize(12).text('Total Amount:', 300, summaryY + 20);
        doc.text(formatCurrency(rental.totalAmount), 440, summaryY + 20, { width: 100, align: 'right' });

        // Payment History
        if (rental.payments && rental.payments.length > 0) {
            doc.moveDown(4);
            doc.fillColor('#1B3A6B').fontSize(12).text('Payment History / பணம் செலுத்திய விவரம்');
            doc.moveDown();
            rental.payments.forEach(p => {
                doc.fillColor('black').fontSize(10).text(`${p.date} - ${p.mode} : ${formatCurrency(p.amount)}`, { indent: 20 });
            });
        }

        doc.end();
    });
};

const generateDriverSalaryStatement = async (driver, salaryRecords, fromDate, toDate) => {
    return new Promise((resolve, reject) => {
        const doc = new PDFDocument({ margin: 50, size: 'A4' });
        const buffers = [];
        
        doc.on('data', buffers.push.bind(buffers));
        doc.on('end', () => resolve(Buffer.concat(buffers)));
        doc.on('error', reject);

        if (isFontValid(FONT_PATH)) {
            doc.font(FONT_PATH);
        } else {
            doc.font('Helvetica');
        }

        // Header
        doc.rect(0, 0, doc.page.width, 100).fill('#1B3A6B');
        doc.fillColor('white').fontSize(24).text('SMART UZHAVAN', 50, 30, { align: 'center' });
        doc.fontSize(12).text('Driver Salary Statement / ஓட்டுநர் சம்பள அறிக்கை', 50, 65, { align: 'center' });

        doc.fillColor('black').moveDown(4);

        // Driver Info
        doc.fontSize(10).fillColor('#1B3A6B').text('Driver Details / விவரம்', 50, 130);
        doc.fillColor('black').text(`Name: ${driver.name}`, 50, 150);
        doc.text(`ID: ${driver.id}`, 50, 165);
        doc.text(`Period: ${fromDate || 'Start'} to ${toDate || 'Present'}`, 350, 150, { align: 'right' });

        // Summary Totals
        const totalNet = salaryRecords.reduce((s, r) => s + (parseFloat(r.netPay) || 0), 0);
        const totalPaid = salaryRecords.reduce((s, r) => s + (r.payments || []).reduce((pSum, p) => pSum + (parseFloat(p.amount) || 0), 0), 0);
        const totalBalance = totalNet - totalPaid;

        doc.rect(50, 200, 150, 60).fill('#F7FAFC');
        doc.fillColor('black').fontSize(10).text('Total Payable', 60, 210);
        doc.fontSize(14).text(formatCurrency(totalNet), 60, 230);

        doc.rect(225, 200, 150, 60).fill('#F0FFF4');
        doc.fillColor('green').fontSize(10).text('Total Received', 235, 210);
        doc.fontSize(14).text(formatCurrency(totalPaid), 235, 230);

        doc.rect(400, 200, 150, 60).fill('#FFF5F5');
        doc.fillColor('red').fontSize(10).text('Balance / நிலுவை', 410, 210);
        doc.fontSize(14).text(formatCurrency(totalBalance), 410, 230);

        // Records Table
        doc.moveDown(8);
        doc.fillColor('#1B3A6B').fontSize(12).text('Salary History (வரிசைப்படியாக)');
        doc.moveDown();

        const tableY = 300;
        doc.fontSize(9).fillColor('black');
        doc.text('Date', 50, tableY);
        doc.text('Base', 120, tableY, { width: 60, align: 'right' });
        doc.text('Bonus', 180, tableY, { width: 60, align: 'right' });
        doc.text('Extra', 240, tableY, { width: 60, align: 'right' });
        doc.text('Adv', 300, tableY, { width: 60, align: 'right' });
        doc.text('Net Pay', 360, tableY, { width: 70, align: 'right' });
        doc.text('Paid', 430, tableY, { width: 60, align: 'right' });
        doc.text('Bal', 490, tableY, { width: 60, align: 'right' });

        let currentY = tableY + 20;
        salaryRecords.forEach(rec => {
            const paid = (rec.payments || []).reduce((sum, p) => sum + p.amount, 0);
            const bal = rec.netPay - paid;

            doc.fontSize(8);
            doc.text(rec.date, 50, currentY);
            doc.text(rec.baseSalary.toFixed(0), 120, currentY, { width: 60, align: 'right' });
            doc.text(rec.bonus.toFixed(0), 180, currentY, { width: 60, align: 'right' });
            doc.text(rec.extraAmount.toFixed(0), 240, currentY, { width: 60, align: 'right' });
            doc.text(rec.advance.toFixed(0), 300, currentY, { width: 60, align: 'right' });
            doc.text(rec.netPay.toFixed(0), 360, currentY, { width: 70, align: 'right' });
            doc.text(paid.toFixed(0), 430, currentY, { width: 60, align: 'right' });
            doc.text(bal.toFixed(0), 490, currentY, { width: 60, align: 'right' });

            currentY += 15;
            if (currentY > 700) {
                doc.addPage();
                currentY = 50;
            }
        });

        doc.fontSize(8).fillColor('#A0AEC0').text('Generated by SmartUzhavan Digital System', 50, 780, { align: 'center' });
        doc.end();
    });
};

const generateOutstandingReport = async (fy, data) => {
    return new Promise((resolve, reject) => {
        const doc = new PDFDocument({ margin: 50, size: 'A4' });
        const buffers = [];
        
        doc.on('data', buffers.push.bind(buffers));
        doc.on('end', () => resolve(Buffer.concat(buffers)));
        doc.on('error', reject);

        if (isFontValid(FONT_PATH)) {
            doc.font(FONT_PATH);
        } else {
            doc.font('Helvetica');
        }

        // Header
        doc.rect(0, 0, doc.page.width, 100).fill('#1B3A6B');
        doc.fillColor('white').fontSize(24).text('SMART UZHAVAN', 50, 30, { align: 'center' });
        doc.fontSize(12).text(`Outstanding Balance Report / நிலுவைத் தொகை அறிக்கை (${fy})`, 50, 65, { align: 'center' });

        doc.fillColor('black').moveDown(4);

        // Grand Totals Summary
        const totalBilled = data.reduce((s, r) => s + (parseFloat(r.total) || 0), 0);
        const totalPaid = data.reduce((s, r) => s + (parseFloat(r.paid) || 0), 0);
        const totalOutstanding = totalBilled - totalPaid;

        doc.rect(50, 120, 150, 50).fill('#F7FAFC');
        doc.fillColor('black').fontSize(9).text('Grand Total Billed', 60, 130);
        doc.fontSize(12).text(formatCurrency(totalBilled), 60, 145);

        doc.rect(225, 120, 150, 50).fill('#F0FFF4');
        doc.fillColor('green').fontSize(9).text('Grand Total Paid', 235, 130);
        doc.fontSize(12).text(formatCurrency(totalPaid), 235, 145);

        doc.rect(400, 120, 150, 50).fill('#FFF5F5');
        doc.fillColor('red').fontSize(9).text('Grand Outstanding', 410, 130);
        doc.fontSize(12).text(formatCurrency(totalOutstanding), 410, 145);

        // Table Header
        const tableY = 200;
        doc.rect(50, tableY, 500, 20).fill('#1B3A6B');
        doc.fillColor('white').fontSize(9);
        doc.text('Farmer (விவசாயி)', 60, tableY + 5);
        doc.text('Village', 180, tableY + 5);
        doc.text('Billed', 280, tableY + 5, { width: 80, align: 'right' });
        doc.text('Paid', 370, tableY + 5, { width: 80, align: 'right' });
        doc.text('Balance', 460, tableY + 5, { width: 80, align: 'right' });

        // Table Rows
        let currentY = tableY + 25;
        doc.fillColor('black');
        data.forEach(row => {
            doc.fontSize(8);
            doc.text(row.label, 60, currentY);
            doc.text(row.village || '-', 180, currentY);
            doc.text(row.total.toFixed(0), 280, currentY, { width: 80, align: 'right' });
            doc.text(row.paid.toFixed(0), 370, currentY, { width: 80, align: 'right' });
            doc.text(row.balance.toFixed(0), 460, currentY, { width: 80, align: 'right' });

            currentY += 15;
            if (currentY > 750) {
                doc.addPage();
                currentY = 50;
            }
        });

        doc.fontSize(8).fillColor('#A0AEC0').text('Generated by SmartUzhavan Digital System', 50, 780, { align: 'center' });
        doc.end();
    });
};

module.exports = { generateHarvesterBill, generateStatement, generateRentalReceipt, generateDriverSalaryStatement, generateOutstandingReport };
